# .travis.yml
language: android
dist: trusty

android:
  components:
    - build-tools-29.0.2
    - android-29

before_install:
  - yes | sdkmanager "build-tools;29.0.2"
  - yes | sdkmanager "platforms;android-29"

script:
  - ./gradlew build check